# Default values for finala.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: similarweb/finala
  tag: 0.3.3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  type: internal

api:
  create: true
  replicas: 1
  annotations: {}
  application:
    log_level: INFO
    storage:
      elasticsearch:
        active: true
        index: general
        username: ""
        password: ""
        endpoint: ""

  service:
    type: ClusterIP
    annotations: {}
    externalPort: 80

  ingress:
    create: false
    host: http://127.0.0.1:8081
    annotations: {}
  
  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

ui:
  create: true
  replicas: 1
  annotations: {}
  application:
    log_level: INFO

  service:
    type: ClusterIP
    annotations: {}
    externalPort: 80
  
  ingress:
    create: false
    host: "https://finala.ui.com"
    annotations: {}

  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

notifier:
  create: true
  schedule: "0 8 * * 1" # Run once a week on Monday at 08:00
  annotations: {}
  environmentVars: 
    # key: value
  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  application:
    log_level: INFO
    notifiers:
      # slack:
      #   token: slack_token
      #   default_channels:
      #     - '#default-channel'
      #   notify_by_tags:
      #     <notification_group>:
      #       minimum_cost_to_present: <minimum price which notifier will notify about>
      #       tags:
      #         - name: name
      #           value: value
      #       notify_to:
      #           - slack username
      #           - '#slack-channelname'

collector:
  create: true
  schedule: "0 8 * * *" # Run every day at 08:00
  annotations: 
    # iam.amazonaws.com/role: arn:aws:iam::ACCOUNT-ID:role/finala-production
  run_at_deployment: true
  environmentVars: 
    # AWS_ACCESS_KEY_ID: value
    # AWS_SECRET_ACCESS_KEY: value
  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  application:
    name: general
    log_level: INFO
    api_server: 
      bulk_interval: 5s
    providers:
      aws:
        accounts: 
          - name: main
            regions:
              - us-east-1
              - us-west-2
        metrics:
          rds:
            - description: Connection count
              metrics:
                - name: DatabaseConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
          docDB:
            - description: Connection count
              metrics:
                - name: DatabaseConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
          elasticache:
            - description: Connection count
              metrics:
                - name: CurrConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0      
          elb:
            - description: Request count
              metrics:
                - name: RequestCount
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d 
              constraint:
                operator: "=="
                value: 0  
          elbv2:
            - description: Request count
              metrics:
                - name: RequestCount
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d 
              constraint:
                operator: "=="
                value: 0    
          ec2:
            - description: CPU utilization 
              metrics:
                - name: CPUUtilization
                  statistic: Maximum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "<"
                value: 6
          dynamodb:
            - description: Provisioned read capacity units
              metrics:
                - name: ConsumedReadCapacityUnits
                  statistic: Sum
                - name: ProvisionedReadCapacityUnits
                  statistic: Average
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                formula: ( ConsumedReadCapacityUnits / 7 / 86400 ) / ProvisionedReadCapacityUnits * 100
                operator: "<"
                value: 80
            - description: Provisioned write capacity units
              metrics:
                - name: ConsumedWriteCapacityUnits
                  statistic: Sum
                - name: ProvisionedWriteCapacityUnits
                  statistic: Average
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                formula: ( ConsumedWriteCapacityUnits / 7 / 86400 ) / ProvisionedWriteCapacityUnits * 100
                operator: "<"
                value: 80
          lambda:
            - description: Invocations count
              metrics:
                - name: Invocations
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
          neptune:
            - description: Requests gremlin/sparql
              metrics:
                - name: GremlinRequestsPerSec
                  statistic: Sum
                - name: SparqlRequestsPerSec
                  statistic: Sum              
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                formula: GremlinRequestsPerSec + SparqlRequestsPerSec
                operator: "=="
                value: 0
          kinesis:
            - description: Total put records
              metrics:
                - name: "PutRecords.Bytes"
                  statistic: Sum
                - name: "PutRecord.Bytes"
                  statistic: Sum              
              period: 24h
              start_time: 168h # 24h * 7d
              constraint:
                # The go module Knetic/govaluate has a built in escaping
                # https://github.com/Knetic/govaluate#escaping-characters
                # [PutRecord.Bytes] will escape the parameter name
                formula: "[PutRecord.Bytes] + [PutRecords.Bytes]"
                operator: "=="
                value: 0              
        resources:
          iamLastActivity:
            enable: true
            description: Last user activity
            global: true
            constraint:
              operator: ">="
              value: 90 # 90 Days
          elasticip:
            enable: true
            description: Not associated
