# Default values for finala.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: similarweb/finala
  tag: 0.2.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  type: internal

api:
  create: true
  replicas: 1
  annotations: {}
  application:
    log_level: INFO
    storage:
      elasticsearch:
        active: true
        index: general
        username: ""
        password: ""
        endpoint: ""

  service:
    type: ClusterIP
    annotations: {}
    externalPort: 80

  ingress:
    create: false
    host: http://127.0.0.1:8081
    annotations: {}
  
  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

ui:
  create: true
  replicas: 1
  annotations: {}
  application:
    log_level: INFO

  service:
    type: ClusterIP
    annotations: {}
    externalPort: 80
  
  ingress:
    create: false
    annotations: {}

  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

collector:
  create: true
  schedule: "* * 1 * *" 
  annotations: 
    # iam.amazonaws.com/role: arn:aws:iam::ACCOUNT-ID:role/finala-production
  run_at_deployment: true
  environmentVars: 
    # AWS_ACCESS_KEY_ID: value
    # AWS_SECRET_ACCESS_KEY: value
  resources:
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  application:
    name: general
    log_level: INFO
    api_server: 
      bulk_interval: 5s
    providers:
      aws:
        accounts: 
          - name: main
            regions:
              - us-east-1
              - us-west-2
        metrics:
          rds:
            - description: Database connection count
              metrics:
                - name: DatabaseConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
          docDB:
            - description: Database connection count
              metrics:
                - name: DatabaseConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
          elasticache:
            - description: connection count
              metrics:
                - name: CurrConnections
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0      
          elb:
            - description: Loadbalancer requests count
              metrics:
                - name: RequestCount
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d 
              constraint:
                operator: "=="
                value: 0  
          elbv2:
            - description: Application Loadbalancer RequestCount
              metrics:
                - name: RequestCount
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d 
              constraint:
                operator: "=="
                value: 0    
          ec2:
            - description: EC2 CPU utilization 
              metrics:
                - name: CPUUtilization
                  statistic: Maximum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "<"
                value: 6
          dynamodb:
            - description: Provisioned read capacity units
              metrics:
                - name: ConsumedReadCapacityUnits
                  statistic: Sum
                - name: ProvisionedReadCapacityUnits
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                formula: ConsumedReadCapacityUnits / ProvisionedReadCapacityUnits * 100 
                operator: "<"
                value: 10
            - description: Provisioned write capacity units
              metrics:
                - name: ConsumedWriteCapacityUnits
                  statistic: Sum
                - name: ProvisionedWriteCapacityUnits
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                formula: ConsumedWriteCapacityUnits / ProvisionedWriteCapacityUnits * 100 
                operator: "<"
                value: 10
          lambda:
            - description: Lambda invocations count
              metrics:
                - name: Invocations
                  statistic: Sum
              period: 24h 
              start_time: 168h # 24h * 7d
              constraint:
                operator: "=="
                value: 0
        resources:
          iamLastActivity:
            description: Last user activity
            global: true
            constraint:
              operator: ">="
              value: 90 # 90 Days
