{{- if .Values.collector.create  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finala.fullname" . }}-configmap-collector
  labels:
{{ include "finala.labels" . | indent 4 }}
  annotations:
{{ include "finala.annotations" . | indent 4 }}
data: 
  config: |-
    ---
    log_level: {{ .Values.collector.application.log_level }}
    name: {{ .Values.collector.application.name }}
    api_server:
      address: http://{{ template "finala.fullname" . }}-api
      bulk_interval: {{ .Values.collector.application.api_server.bulk_interval }}
    providers:
      aws: 
        {{- toYaml .Values.collector.application.providers.aws.accounts | nindent 6 -}}
        {{- if .Values.collector.application.providers.aws.metrics }}
        {{- toYaml .Values.collector.application.providers.aws.metrics | nindent 6 -}}
        {{- else -}}
        {{ .Files.Get "aws-metrics.yaml" | nindent 6 }}
        {{- end }}
{{- end -}}
