{{- $root := . -}}
{{range $name, $collector := .Values.collector }}
{{- if $collector.create  }}
{{ $resourceName := printf "%s-%s-configmap-collector" (include "finala.fullname" $root) $name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $resourceName }}
  labels:
{{ include "finala.labels" $root | indent 4 }}
  annotations:
{{ include "finala.annotations" $root | indent 4 }}
data: 
  config: |-
    ---
    log_level: {{ $collector.application.log_level }}
    name: {{ $name }}
    api_server:
      address: http://{{ template "finala.fullname" $root }}-api
      bulk_interval: {{ $collector.application.api_server.bulk_interval }}
    providers:
      aws: 
        accounts:
          {{- toYaml $collector.application.providers.aws.accounts | nindent 8 -}}
          {{- if $collector.application.providers.aws.metrics }}
          {{- toYaml $collector.application.providers.aws.metrics | nindent 8 -}}
          {{- else -}}
          {{ $root.Files.Get "aws-metrics.yaml" | nindent 8 }}
          {{- end }}
{{- end }}
{{- end }}
