{{- if .Values.api.create  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "finala.fullname" . }}-api
  labels:
{{ include "finala.labels" . | indent 4 }}
  annotations:
{{- if .Values.api.service.annotations }}
{{ toYaml .Values.api.service.annotations | indent 4 }}
{{- end }}
{{ include "finala.annotations" . | indent 4 }}
spec:
  selector:
{{ include "finala.matchLabels" . | indent 4 }}
    component: {{ include "finala.fullname" . }}-api
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: 8081
    name: "http"
{{- end -}}
